[default]
cookie_secure = false

[default.db]
host = "localhost"
port = 5433
name = "lanterna_magica"
user = "lanterna_magica"
password = "lanterna_magica"

[default.server]
host = "0.0.0.0"
port = 8000

[default.cors]
allow_origins = ["http://localhost:3000"]
allow_credentials = true

[default.otel]
endpoint = ""
service_name = "lanterna-magica"

[development]
dynaconf_merge = true

[testing]
dynaconf_merge = true

[testing.db]
name = "lanterna_magica_test"
user = "lanterna_magica_test"
password = "lanterna_magica_test"

[production]
dynaconf_merge = true
cookie_secure = true
log_json = true

[production.cors]
allow_origins = []
allow_credentials = false

[production.db]
host = "db"
port = 5432

[production.otel]
endpoint = ""
service_name = "lanterna-magica-prod"
